=== eclipse-archived/unide/servers/rest/resources/process_message_v2.json
{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"type": "object",
	"properties": {
		"content-spec": {
			"type": "string"
		},
		"device": {
			"type": "object",
			"properties": {
				"deviceID": {
					"type": "string"
				},
				"operationalStatus": {
					"type": "string"
				},
				"metaData": {
					"type": "object"
				}
			},
			"additionalProperties": false,
			"required": [
				"deviceID"
			]
		},
		"part": {
			"type": "object",
			"properties": {
				"type": {
					"type": "string"
				},
				"partTypeId": {
					"type": "string"
				},
				"id": {
					"type": "string"
				},
				"result": {
					"type": "string"
				},
				"code": {
					"type": "string"
				},
				"metaData": {
					"type": "object"
				}
			},		
		"additionalProperties": false,
		"required": [
			"id"
		]
	},
	    "process": {
      "type": "object",
      "properties": {
        "externalProcessId": {
          "type": "string"
        },
        "ts": {
          "type": "string"
        },
        "result": {
          "type": "string"
        },
        "shutoffPhase": {
          "type": "string"
        },
        "program": {
          "type": "object",
          "properties": {
            "id": {
              "type": "string"
            },
            "name": {
              "type": "string"
            },
            "lastChangedDate": {
              "type": "string"
            }
          }
        },
        "shutoffValues": {
	        "type": "object",
	        "items": {
	          	"type": "object",
				"properties": {
				  "ts": {
				    "type": "string"
				  },
				  "value": {
				    "type": "number"
				  },
				  "upperError": {
				    "type": "number"
				  },
				  "LowerError": {
				    "type": "number"            
				  },
				  "upperWarn": {
				    "type": "number"
				  },
				  "LowerWarn": {
				    "type": "number"            
				  }
				},	
				"additionalProperties": false
	        }
	     },
        "metaData": {
          "type": "object"
        }
      },
      "required": [
        "ts"       
      ]
    },
    "measurements": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "ts": {
            "type": "string"
          },
          "phase": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "result": {
            "type": "string"
          },
          "code": {
            "type": "string"
          },
          "limits": {
	          "type": "object",
		        "items": {
	            "type": "object",
				"properties": {
				  "upperError": {
				    "type": "object"
				  },
				  "LowerError": {
				    "type": "object"            
				  },
				  "upperWarn": {
				    "type": "object"
				  },
				  "LowerWarn": {
				    "type": "object"            
				  }
				},	
				"additionalProperties": false            
	          }
          },
        "specialValues": {
	        "type": "object",
	        "items": {
	          	"type": "object",
				"properties": {
				  "time": {
				    "type": "object"
				  },
				  "value": {
				    "type": "object"
				  }
				},
				"required": [
		          "value"
		        ],	
				"additionalProperties": false
	        }
	     },
          "series": {
            "type": "object"
          }
        },
        "required": [
          "ts",
          "series"
        ],
      	"additionalProperties":false
      }
    }
    },	
	"additionalProperties": false,
	"required": [
		"content-spec",
		"device",
		"measurements"
	]
}

=== eclipse-archived/unide/bindings/ppmp-java-binding/src/test/resources/process.json
{
    "content-spec" : "urn:spec://eclipse.org/unide/process-message#v2",
    "device" : {
        "deviceID" : "a4927dad-58d4-4580-b460-79cefd56775b",
        "operationalStatus" : "normal",
        "metaData" : {
            "swVersion" : "2.0.3.13",
            "swBuildId" : "41535"   
        }
    },
    "part" : {
        "type" : "single",
        "partTypeId" : "F00VH07328",
        "id" : "420003844",
        "result" : "NOK",
        "code" : "HUH289",
        "metaData" : {
             "toolId" : "32324-432143"
        }
    },
    "process" : {
        "externalProcessId" : "b4927dad-58d4-4580-b460-79cefd56775b",
        "ts" : "2002-05-30T09:30:10.123+02:00",
        "result" : "NOK",
        "shutoffPhase" : "phase 1",
        "program" : {
            "id" : "1",
            "name" : "Programm 1",
            "lastChangedDate" : "2002-05-30T09:30:10.123+02:00"
        },
        "shutoffValues" : {
            "force" : {
                "ts" : "2002-05-30T09:30:11.123+02:00",
                "value" : 24,
                "upperError" : 26,
                "lowerError" : 22
            },
            "pressure" : {               
                "value" : 50,
                "upperError" : 52,
                "lowerError" : 48
            }
        },
        "metaData" : {
            "name" : "Getriebedeckel verschrauben"
        }
    },
    "measurements" : [
        {
            "ts" : "2002-05-30T09:30:10.123+02:00",
            "phase" : "phasen name 2",
            "name" : "500 Grad links drehen",
            "result" : "NOK",
            "code" : "0000 EE01",
            "limits" : {
                "temperature" : {
                    "upperError" :  4444,
                    "lowerError" :  44,
                    "upperWarn"    :  2222,
                    "lowerWarn"    :  46,
                    "target" :  35  
                }
            },
            "specialValues" : {
                "pressure" : {
                    "time" : 24,
                    "value" : 44.2432
                },
                "force" :  {
                    "time" : 24,
                    "value" : 24
                }
            },
            "series" : {
                "time" : [0, 23, 24],
                "force" : [26, 23, 24],
                "pressure" : [52.4, 46.32, 44.2432],
                "temperature" : [45.4243, 46.42342, 44.2432]          
            }
        },
        {
            "ts" : "2002-05-30T09:30:10.123+02:00",
            "phase" : "phasen name",
            "result" : "OK",    
            "limits" : {
                "force" : {
                    "upperError" : [27, 24, 25],
                    "lowerError" : [25, 22, 23]
                },
                "pressure" : {
                    "upperError" : [54, 48, 46],
                    "lowerError" : [50, 44, 42]
                }
            },
            "specialValues" : {
                "pressure" : {
                    "value" : 24
                },
                "force" : {
                    "value": 50
                }
            },
            "series" : {
                "time" : [30, 36, 42],
                "force" : [26, 23, 24],
                "pressure" : [52.4, 46.32, 44.2432],
                "temperature" : [45.4243, 46.42342, 44.2432]           
            }
        }
    ]
}
